### ISSUE TITLE
user directly redirects to login-then-dashboard after registration

### ISSUE THREAD

**Issue by aayushxrj** [aayushxrj/Password-Buddy#15]
Commit [b85bdea](https://github.com/aayushxrj/Password-Buddy/commit/b85bdea317569411d886622ac7fb92244c340d0b) causes this issue which resolved the issue #7.

**Comment by Sdaewa** [comment]
Can I take care of this?

**Comment by aayushxrj** [comment]
@Sdaewa Thanks for contributing but your [PR](https://github.com/aayushxrj/Password-Buddy/pull/18) still doesn't resolve the issue. The user should proceed and stay on login.html after registration. 
The issue is that it does proceed to login.html but then redirects to dashboard.html, this happens most probably due to piece of code added in the Issue #7 in login.js -
``` 
onAuthStateChanged(auth, (user) => {
    if (user) {
        document.getElementById("error-msg").style.display = "block";
        document.getElementById("error-msg").innerHTML = "Welcome back! Redirecting...";
        window.location.href = "dashboard.html";
    }
});
```
This code checks if the session(cookie) already exists and thus after clicking login on the header, directly redirects to dashboard.html.
I think this is interfering with our code, maybe the browser stores the session(cookie) after registration and thus when it redirects to login.html after registration , it already finds the session and decides to redirect to dashboard.html

**Comment by aayushxrj** [comment]
Commit  [a5dbaa6](https://github.com/aayushxrj/Password-Buddy/commit/a5dbaa63b3f8fc8cc492bc97e5b22c2fac00d55c) resolved this issue.
