### ISSUE TITLE
API Key is not saved in .env file

### ISSUE THREAD

**Issue by Sdaewa** [aayushxrj/Password-Buddy#17]
Hi @aayushxrj, I have checked the API keys are public. I am requesting permission to move them to the correct file

**Comment by aayushxrj** [comment]
@Sdaewa Thanks for showing interest but I think this is the same issue as #13 .
If you store the api_keys and firebaseConfig stuff in the .gitignore, the firebase-hosting may not work as my project is hosted directly from my GitHub repo.
