### ISSUE TITLE
dropdown menu transition doesn't work anymore

### ISSUE THREAD

**Issue by aayushxrj** [aayushxrj/Password-Buddy#22]
[PR](https://github.com/aayushxrj/Password-Buddy/pull/21) caused this issue.

### Transition desired:
https://user-images.githubusercontent.com/111623667/233798141-f6a94929-8553-4dc2-8baa-ffe5e481a0f9.mp4

Code that worked before this PR :
```
.dropdown-menu ul{
  position: relative;
  width: 100px;
  padding-left: 15px;
  display: flex;
  justify-content: space-around;
  align-items: center;
  flex-direction: column;
  list-style: none;
  border: 1px solid #eff2f5;
  border-radius: 3px;
  overflow: hidden;
  box-shadow: 0 0 10px 0 rgb(62 28 131 / 25%);
  opacity: 0;
  pointer-events: none;
  transform: translateY(-10px);
  transition: all 0.4s ease;
}
.dropdown-menu button:focus + ul{
  opacity: 1;
  pointer-events: all;
  transform: translateY(10px);
}
```
<br>
### Issue in transistion:

https://user-images.githubusercontent.com/111623667/233798319-a677c367-3dec-4d70-9025-94006aba5a02.mp4

**Comment by pravinargade18** [comment]
Hey @aayushxrj ! I'm creating PR please check it and merge if correct :)

**Comment by aayushxrj** [comment]
[PR](https://github.com/aayushxrj/Password-Buddy/pull/25) by @Udassi-Pawan resolved the issue.
