### ISSUE TITLE
Improve Registration Form Error Messages

### ISSUE THREAD

**Issue by Frenziecodes** [aayushxrj/Password-Buddy#24]
The error messages displayed on the registration form are not clearly visible, as they have the same color as the form fields. This causes confusion for users who have missed a required field and are not sure what they need to correct.

To improve user experience, we need to change the styling of the error messages to make them more noticeable. One possible solution is to change the color of the error messages to red and display them in bold.

**Comment by aayushxrj** [comment]
@lewisushindi Thanks for the suggestion. Commit 27eda92 resolves the issue.
